<html>
<head>
<title> Ejemplo 2 </title>
<body>

<?php
//Inicialización del vector
$Empleado[0] = 4371;
$Empleado [1] = "Jara Martinez";
$Empleado [2] = "48.735.594";
$Empleado[3] = 1429.54;
$Empleado[4] = "Arquitecto";

//Impresión del vector
echo("Legajo:".$Empleado[0]. "<br>");
echo("Nombre:".$Empleado[1]. "<br>");
echo("DNI:".$Empleado[2]. "<br>");
echo("Sueldo:".$Empleado[3]. "<br>");
echo("Profesión:".$Empleado[4]. "<br>");
?>
</body>
</html>
