<HTML>
<HEAD>
 <title>Nuevo Documento</TITLE>
</HEAD>
<BODY>
<?php
  $num1 =8;
  $num2 =5;
  printf ("la suma de $num1 y $num2 es: <b>%d</b><br>", $num1 + $num2);
  printf("la resta de $num1 y $num2 es: <b>%d</b><br>", $num1 - $num2);
  printf("la multiplicación de $num1 y $num2 es: <b>%d</b><br>", $num1 * $num2);
  printf("la división de $num1 y $num2 es: <b>%0.2f</b><br>", $num1 / $num2);
  printf("El módulo de $num1 y $num2 es: <b>%0.1f</b><br>", $num1 % $num2);
  
?>
</BODY>
</HTML>
